package recipes

import "time"

// Recipe represents a cooking recipe created or generated by a user.
type Recipe struct {
	ID          int64
	Title       string
	Description string
	Ingredients []string
	Steps       []string
	Tags        []string
	CreatedBy   int64
	CreatedAt   time.Time
	UpdatedAt   time.Time
}
